image: python

stages:
  - build
  - test


audoma-build:
  stage: build
  script:
    - python3 --version
    - echo "hello world"
    - pip install ./
    - pip install -r requirements_dev.txt


audoma-test:
  stage: test
  script:
    - cd audoma_examples/drf_example
    - python3 manage.py test


audoma-static:
  stage: test
  script:
    - ./static_analysis.sh
