image: python

stages:
  - build
  - test


audoma-build:
  stage: build
  script:
    - python3 --version
    - echo "hello world"
    - pip install ./
    - pip install -r requirements_dev.txt


audoma-test:
  stage: test
  script:
    - echo "---> Building test image and running tests"
    - cd docker && docker-compose --project-name=$CI_BUILD_ID run --rm tests
  after_script:
    - echo "---> Cleaning up"
    - cd docker
    - >
      docker-compose --project-name=$CI_BUILD_ID down
      && docker-compose --project-name=$CI_BUILD_ID kill
      && docker-compose --project-name=$CI_BUILD_ID rm -fvs
      && docker rmi audoma-tests-$CI_BUILD_ID

audoma-static:
  stage: test
  script:
    - ./static_analysis.sh
