image: python

stages:
  - build
  - test


audoma-build:
  stage: build
  script:
    - python3 --version
    - echo "hello world"
    - pip install ./


audoma-test:
  stage: test
  script:
    - cd audoma_examples/drf_example
    - python3 manage.py test