repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args: [-i, -r, --remove-unused-variables]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
