version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf

build:
  image: latest


python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
