# Generated by Django 4.0 on 2025-01-22 13:35

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare_api", "0002_prescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.ManyToManyField(to="healthcare_api.Specialization"),
        ),
    ]
