# Generated by Django 4.1.5 on 2023-02-20 08:21
from django.db import migrations

import audoma.django.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare_api", "0002_prescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="height",
            field=audoma.django.db.fields.DecimalField(
                decimal_places=13, max_digits=23
            ),
        ),
    ]
