version: '3'

services:
  tests:
    image: audoma-tests-${CI_BUILD_ID}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: tox

  example_app:
    image: example_app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
    command:
      - cd audoma_examples/drf_example
      - python manage.py runserver

    volumes:
      - .:../audoma
    ports:
      - 8000:8000
