FROM python:3.9-buster

RUN mkdir audoma
WORKDIR /audoma
COPY ./requirements/base.txt /audoma/requirements/base.txt
COPY ./requirements/dev.txt /audoma/requirements/dev.txt
RUN pip install --upgrade pip
RUN pip install -r /audoma/requirements/base.txt
RUN pip install -r /audoma/requirements/dev.txt
