version: '3'

services:
  tests:
    image: audoma-tests
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: tox

  coverage:
    image: audoma-tests
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    working_dir: /audoma/audoma_examples/drf_example/
    command: bash -c "coverage run manage.py test audoma audoma_api && coverage report"

  sqlite3:
    image: nouchka/sqlite3:latest
    volumes:
      - ../sqlite/db:/var/lib/sqlite/db
    environment:
      - SQLITE_DB=db/db.sqlite3

  example_app:
    image: example_app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
    volumes:
      - ..:/audoma
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    command: bash -c "cd audoma_examples/drf_example && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - sqlite3
