version: '3'

services:
  tests:
    image: audoma-tests-${CI_BUILD_ID}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: tox

  example_app:
    image: example_app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
    volumes:
      - ..:/audoma
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    command: bash -c " PYTHONUNBUFFERED=True cd audoma_examples/drf_example && python manage.py runserver 0.0.0.0:8000"
