# Generated by Django 3.2.12 on 2022-04-01 10:27

import jsonfield.fields
import macaddress.fields
import phonenumber_field.modelfields

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleFileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_field", models.FileField(upload_to="")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_field", models.CharField(max_length=255)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("url", models.URLField()),
                ("boolean", models.BooleanField()),
                ("nullboolean", models.BooleanField(null=True)),
                ("mac_adress", macaddress.fields.MACAddressField(integer=True)),
                ("slug", models.SlugField()),
                ("uuid", models.UUIDField()),
                ("ip_address", models.GenericIPAddressField()),
                ("integer", models.IntegerField()),
                ("_float", models.FloatField()),
                ("decimal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("datetime", models.DateTimeField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("duration", models.DurationField()),
                (
                    "choices",
                    models.IntegerField(
                        choices=[(1, "example 1"), (2, "example 2"), (3, "example 3")]
                    ),
                ),
                ("json", jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleSimpleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("value", models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleTagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="audoma_api.examplesimplemodel",
                    ),
                ),
            ],
        ),
    ]
