# Generated by Django 4.0.4 on 2022-05-13 17:08

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import audoma.django.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("audoma_api", "0002_alter_examplemodel_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", audoma.django.db.fields.CharField(max_length=255)),
                ("first_name", audoma.django.db.fields.CharField(max_length=225)),
                ("last_name", audoma.django.db.fields.CharField(max_length=255)),
                (
                    "phone_number",
                    audoma.django.db.fields.PhoneNumberField(
                        max_length=128, region="PL"
                    ),
                ),
                ("nationality", audoma.django.db.fields.CharField(max_length=255)),
                ("city", audoma.django.db.fields.CharField(max_length=255)),
                ("email", audoma.django.db.fields.EmailField(max_length=254)),
                ("bio", audoma.django.db.fields.TextField()),
                ("is_active", audoma.django.db.fields.BooleanField()),
                ("mac_adress", audoma.django.db.fields.MACAddressField(integer=True)),
                ("ip_address", audoma.django.db.fields.GenericIPAddressField()),
                ("age", audoma.django.db.fields.IntegerField()),
                ("_float", audoma.django.db.fields.FloatField()),
                (
                    "decimal",
                    audoma.django.db.fields.DecimalField(
                        decimal_places=2, max_digits=10
                    ),
                ),
                ("duration", audoma.django.db.fields.DurationField()),
                (
                    "account_type",
                    audoma.django.db.fields.IntegerField(
                        choices=[(1, "facebook"), (2, "gmail"), (3, "other")]
                    ),
                ),
                (
                    "account_balance_currency",
                    audoma.django.db.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("GBP", "British Pound"),
                            ("CNY", "Chinese Yuan"),
                            ("EUR", "Euro"),
                            ("INR", "Indian Rupee"),
                            ("JPY", "Japanese Yen"),
                            ("NZD", "New Zealand Dollar"),
                            ("CHF", "Swiss Franc"),
                            ("USD", "US Dollar"),
                        ],
                        default="PLN",
                        max_length=3,
                    ),
                ),
                (
                    "account_balance",
                    audoma.django.db.fields.MoneyField(
                        decimal_places=2, default_currency="PLN", max_digits=14
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", audoma.django.db.fields.TextField()),
                (
                    "price_currency",
                    audoma.django.db.fields.CurrencyField(
                        choices=[
                            ("AUD", "Australian Dollar"),
                            ("GBP", "British Pound"),
                            ("CNY", "Chinese Yuan"),
                            ("EUR", "Euro"),
                            ("INR", "Indian Rupee"),
                            ("JPY", "Japanese Yen"),
                            ("NZD", "New Zealand Dollar"),
                            ("CHF", "Swiss Franc"),
                            ("USD", "US Dollar"),
                        ],
                        default="PLN",
                        max_length=3,
                    ),
                ),
                (
                    "price",
                    audoma.django.db.fields.MoneyField(
                        decimal_places=2, default_currency="PLN", max_digits=14
                    ),
                ),
                ("file_field", models.FileField(upload_to="")),
                ("posted_at", audoma.django.db.fields.DateTimeField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audoma_api.account",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ExampleFileModel",
        ),
        migrations.DeleteModel(
            name="ExampleModel",
        ),
        migrations.DeleteModel(
            name="ExamplePerson",
        ),
    ]
