# Generated by Django 4.0.4 on 2022-05-17 08:03

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import audoma.django.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("audoma_api", "0003_account_auction_delete_examplefilemodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleSimpleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", audoma.django.db.fields.CharField(max_length=64)),
                ("value", audoma.django.db.fields.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", audoma.django.db.fields.CharField(max_length=255)),
                ("slug_name", audoma.django.db.fields.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=audoma.django.db.fields.PhoneNumberField(max_length=128, region="IT"),
        ),
        migrations.CreateModel(
            name="ExampleTagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", audoma.django.db.fields.CharField(max_length=32)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="audoma_api.examplesimplemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", audoma.django.db.fields.CharField(max_length=255)),
                (
                    "body_type",
                    audoma.django.db.fields.IntegerField(
                        choices=[
                            (1, "Sedan"),
                            (2, "Coupe"),
                            (3, "Hatchback"),
                            (4, "Pickup Truck"),
                        ]
                    ),
                ),
                ("engine_size", audoma.django.db.fields.FloatField()),
                (
                    "engine_type",
                    audoma.django.db.fields.IntegerField(
                        choices=[
                            (1, "Petrol"),
                            (2, "Diesel"),
                            (3, "Electric"),
                            (4, "Hybrid"),
                        ]
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audoma_api.manufacturer",
                    ),
                ),
            ],
        ),
    ]
