name: Audoma build

on: [push]

jobs:
 audoma-build:
  runs-on: ubuntu-latest # os for running the job
  steps:
    - name: Install audoma
      working-directory: ../../
      run: |
        python3 --version
        echo "hello world"
        echo pwd
        pip install ./
        pip install -r requirements_dev.txt
