name: Audoma build

on: [push]

jobs:
 audoma-build:
  runs-on: ubuntu-latest # os for running the job
  steps:
    - run: |
      python3 --version
      echo "hello world"
      pip install ./
      pip install -r requirements_dev.txt
