name: Audoma test

on: [push]

jobs:
  audoma-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          echo "---> Building test image and running tests"
          docker-compose -f docker/docker-compose.yml build
      - name: Run tests
        run: |
          echo "---> Building test image and running tests"
          docker-compose -f docker/docker-compose.yml run --rm tests
      - name: Run test coverage report
        run: |
            echo "---> Building test image and running tests"
            docker-compose -f docker/docker-compose.yml run --rm coverage
      - name: Install dependencies
        run: pip install -r requirements_dev.txt
      - name: Run static analysis
        run: ./static_analysis.sh
